### ISSUE TITLE
Error with 1.3.2

### ISSUE THREAD

**Issue by XhmikosR** [pierreinglebert/node-zopfli#43]
```
module.js:338
    throw err;
          ^
Error: Cannot find module '../build/Release/zopfli'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\xmr\AppData\Roaming\npm\node_modules\node-zopfli\bin\zopflipng:7:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
```

**Comment by pierreinglebert** [comment]
io.js ?
Le 4 mai 2015 12:06 AM, "XhmikosR" <notifications@github.com> a écrit :
>
> module.js:338
>     throw err;
>           ^
> Error: Cannot find module '../build/Release/zopfli'
>     at Function.Module._resolveFilename (module.js:336:15)
>     at Function.Module._load (module.js:278:25)
>     at Module.require (module.js:365:17)
>     at require (module.js:384:17)
>     at Object.<anonymous>
(C:\Users\xmr\AppData\Roaming\npm\node_modules\node-zopfli\bin\zopflipng:7:14)
