### ISSUE TITLE
missing node-v44-linux-arm binding error

### ISSUE THREAD

**Issue by silverwind** [pierreinglebert/node-zopfli#56]
Looks like I'm missing a `node-v44-linux-arm` binding, `node-v43-linux-arm` seems to be there and the module did install without an error. Any ideas?

```console
$ node -v
v2.5.0
$ npm -v
2.13.2
$ npm ls node-zopfli
droppy@2.3.15 /srv/droppy/app
└── node-zopfli@1.3.4
$ node /srv/droppy/app/droppy.js start
module.js:338
    throw err;
          ^
Error: Cannot find module '/srv/droppy/app/node_modules/node-zopfli/lib/binding/node-v44-linux-arm/zopfli.node'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/srv/droppy/app/node_modules/node-zopfli/lib/zopfli.js:7:14)
    at Module._compile (module.js:430:26)
    at Object.Module._extensions..js (module.js:448:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
$ ls /srv/droppy/app/node_modules/node-zopfli/lib/binding/
node-v43-linux-arm  node-v44-darwin-x64
```

**Comment by pierreinglebert** [comment]
node-v43 is for io.js 1.x and node-v44 is for io.js 2.x. Did you install it with io.js 1.x and upgraded to 2.x without running `npm rebuild` in your project ?

**Comment by silverwind** [comment]
Indeed there was some sort of upgrade issue. After deleting `node_modules` and npm's cache, it works now. Thanks!
