### ISSUE TITLE
Does not work on RHEL6?

### ISSUE THREAD

**Issue by grahamb** [pierreinglebert/node-zopfli#60]
node-zopfli does not appear to work on RHEL6. It seems to have a dependency on glibc 2.14, and the supported version in RHEL6 is 2.12.

This is impacting Simon Fraser University's (github/sfu) ability to deploy our Learning Managment System, instructure/canvas-lms, since it now has a dependency on node-zopfli (via ryankshaw/brandable_css).

```
DEPRECATION WARNING: You have Rails 2.3-style plugins in vendor/plugins! Support for these plugins will be removed in Rails 4.0. Move them out and bundle them in your Gemfile, or fold them in to your app as lib/myplugin/* and config/initializers/myplugin.rb. See the release notes for more on this: http://weblog.rubyonrails.org/2012/1/4/rails-3-2-0-rc2-has-been-released. (called from <top (required)> at /tmp/canvas-lms/Rakefile:11)
--> Starting: 'Making sure node_modules are up to date'
--> Finished: 'Making sure node_modules are up to date' in 4.800319236
--> Starting: 'compile css (including custom brands)'
module.js:522
  var nodePath = process.env['NODE_PATH'];
                        ^
Error: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /tmp/canvas-lms/node_modules/brandable_css/node_modules/node-zopfli/lib/binding/node-v14-linux-x64/zopfli.node)
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/tmp/canvas-lms/node_modules/brandable_css/node_modules/node-zopfli/lib/zopfli.js:7:14)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/tmp/canvas-lms/node_modules/brandable_css/lib/handleGzip.js:11:37)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
--> Finished: 'compile css (including custom brands)' in 1.171742863
```

**Comment by pierreinglebert** [comment]
It's because of the prebuilt binary.
To avoid the compiling step on windows and osx (these users usually don't have gcc or VS2013), prebuilt binaries are sent on a s3 bucket and downloaded at the installation.
The prebuilt binary for linux is compiled on ubuntu 14.04 so it doesn't work properly on your RHEL, I deleted them on the s3 bucket so if you reinstall it, it will compile and it will work.

**Comment by grahamb** [comment]
Thanks, that worked.
