### ISSUE TITLE
Failed at the node-zopfli@1.4.0 install script

### ISSUE THREAD

**Issue by guar47** [pierreinglebert/node-zopfli#99]
Hello everybody.
I tried to install dependencies at my project, but it fails on `node-zopfli@1.4.0 install script`. Could you take a look at the errors?

```
34516 verbose stack Error: node-zopfli@1.4.0 install: `node-pre-gyp install --fallback-to-build`
34516 verbose stack Exit status 1
34516 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
34516 verbose stack     at EventEmitter.emit (events.js:182:13)
34516 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
34516 verbose stack     at ChildProcess.emit (events.js:182:13)
34516 verbose stack     at maybeClose (internal/child_process.js:962:16)
34516 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
34517 verbose pkgid node-zopfli@1.4.0
34518 verbose cwd [local path]
34519 verbose Darwin 18.0.0
34520 verbose argv "/usr/local/Cellar/node/11.0.0/bin/node" "/usr/local/bin/npm" "install" "--no-package-lock"
34521 verbose node v11.0.0
34522 verbose npm  v6.4.1
34523 error code ELIFECYCLE
34524 error errno 1
34525 error node-zopfli@1.4.0 install: `node-pre-gyp install --fallback-to-build`
34525 error Exit status 1
34526 error Failed at the node-zopfli@1.4.0 install script.
```

**Comment by pierreinglebert** [comment]
I think you should try to install v2.0.3 instead of v1.x, these versions were designed to work on node 0.12
